set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(path "${CMAKE_CURRENT_LIST_DIR}/../../x86_64-linux-musl/bin/x86_64-linux-musl-")
get_filename_component(CMAKE_C_COMPILER "${path}gcc" ABSOLUTE CACHE)
get_filename_component(CMAKE_CXX_COMPILER "${path}g++" ABSOLUTE CACHE)
