set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR armv6)
set(path "${CMAKE_CURRENT_LIST_DIR}/../../armv6-linux-musleabihf/bin/armv6-linux-musleabihf-")
get_filename_component(CMAKE_C_COMPILER "${path}gcc" ABSOLUTE CACHE)
get_filename_component(CMAKE_CXX_COMPILER "${path}g++" ABSOLUTE CACHE)
