name: Continuous Integration

on: { push: { tags-ignore: ["**"] } }

env:
  VCPKG_COMMIT: "a1cae005c39be7b18ba319fced856b68d7276271"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-26.04, windows-2025]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v7

    - name: Setup MSVC
      if: startsWith(matrix.os, 'windows-')
      uses: eden-ci/msvc-dev-cmd@1bd71f95d6f3d1b2b3395b335cc63bcdc90cf223
      with: { arch: amd64 }

    - name: Setup GCC
      if: startsWith(matrix.os, 'ubuntu-')
      run: .github/scripts/setup-gcc.sh 16

    - name: Install vcpkg
      uses: friendlyanon/setup-vcpkg@v1
      with:
        cache-version: ${{ matrix.os }}
        committish: ${{ env.VCPKG_COMMIT }}

    - name: Configure
      shell: pwsh
      run: cmake "--preset=ci-$("${{ matrix.os }}".split("-")[0])"

    - name: Build
      run: cmake --build build
